contributors/urls.py
from django.views import generic


from django.urls import path
from .views import (
            ContributorListView,
            CreateContributorView,
        )

app_name = 'contributors'
urlpatterns = [
    path('', generic.TemplateView.as_view(template_name='contributors/home.html'), name='home'),
    path('thank-you', generic.TemplateView.as_view(template_name='contributors/thank_you.html'), name='thank_you'),
    path('create-contributor', CreateContributorView.as_view(), name='create_contributor'),
    path('contributor-list', ContributorListView.as_view(), name='contributor_list'),
    path('contributor-list', ContributorListView.as_view(), name='contributor_list'),
]

nescode/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contributors.urls', namespace = 'contributors')),
    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contributors/models.py
from django.db import models


ROLE_CHOICES = (
    ('developer', 'developer'),
    ('designer', ' designer'),
    ('documentation team', 'documentation team'),
)


class CreateContributor(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=13)
    resume = models.FileField(upload_to='resumes')
    contributed = models.BooleanField(default=False)
    role = models.CharField(choices=ROLE_CHOICES, max_length=25)
    about = models.CharField(max_length=255)

    def __str__(self):
        return self.name

contributors/forms.py
from django import forms


ROLE_CHOICES = (
    ('developer', 'as a developer'),
    ('designer', 'as a designer'),
    ('documentation team', 'as a documentation team'),
)


class ContributeForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField(max_length=255)
    phone = forms.CharField(max_length=13)
    role = forms.ChoiceField(widget=forms.RadioSelect, choices=ROLE_CHOICES)
    about = forms.CharField(max_length=255)
    resume = forms.FileField()

contributors/views.py
from django.shortcuts import render, redirect
from .forms import ContributeForm
from .models import CreateContributor
from django.views.generic.list import ListView
from django.views.generic import View


class CreateContributorView(View):
    def post(self, *args, **kwargs):
        form = ContributeForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            contributor_object = CreateContributor(name=form.cleaned_data['name'],
                                                   email=form.cleaned_data['email'],
                                                   phone=form.cleaned_data['phone'],
                                                   role=form.cleaned_data['role'],
                                                   resume=form.cleaned_data['resume'],
                                                   about=form.cleaned_data['about']
                                                   )
            contributor_object.save()
            return redirect('/thank-you')

    def get(self, *args, **kwargs):
        context = {
            'form': ContributeForm()
        }
        return render(self.request, 'contributors/create_contributor.html', context)


class ContributorListView(ListView):
    model = CreateContributor
    paginate_by = 4
    ordering = ['-id']
    queryset = CreateContributor.objects.filter(contributed=True)
    template_name = 'contributors/contributor_list.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        {% include 'template_blocks/head_css.html' %}

        {% block extra_head %}
        {% endblock %}
    </head>
        <body>
        {% include 'template_blocks/navbar.html' %}
        {% block body %}

        {% block content %}
        {% endblock content %}

        {% endblock body %}

        {% block extra_body %}
        {% endblock extra_body%}

        {% include 'template_blocks/footers.html' %}
        {% include 'template_blocks/javascript.html' %}
        {% block extra_scripts %}
        {% endblock extra_scripts %}
    </body>
</html>

templates/contributors/contributor_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if object_list %}
<div class="col-sm-12 col-md-8 col-lg-6 mx-auto mb-5">
    <table class="table table-borderless">
        <thead>
        <tr>
             <th style="width: 33.33%">SI NO</th>
             <th style="width: 33.33%">Name</th>
             <th style="width: 33.33%">Contribution</th>
        </tr>
        </thead>
        <tbody >
        <tr> {% for contributor in object_list %}
            {% if contributor.contributed %}
            <th scope="row"><a href="" class="h6">{{ forloop.counter0|add:page_obj.start_index }}</a></th>
            <td><a class=h6 href="" data-toggle="popover" data-placement="bottom" title="{{ contributor.name }}"
                   data-content="{{ contributor.about }}" data-trigger="hover">{{ contributor.name }}</a></td>
            <td><a class=h6 href="" data-toggle="popover" data-placement="bottom" title="{{ contributor.name }}"
                   data-content="{{ contributor.about }}" data-trigger="hover">{{ contributor.get_role_display }}</a></td>
        </tr>
        {% endif %}
        {% endfor %}
        </tbody>
    </table>
</div>

<!--pagination starts-->
    {% if is_paginated %}
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
              {% endif %}

              {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                <!--<li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>-->
              <a class="btn btn-primary mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
              <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
              {% endfor %}

              {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
              {% endif %}
          </ul>
        </nav>
        {% endif %}
    {% endif %}
{% endblock content %}

{% block extra_scripts %}
    <script>
     $(document).ready(function(){
            $('[data-toggle="popover"]').popover();
        });
    </script>
{% endblock extra_scripts %}

templates/contributors/create_contributor.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div>
        <div class="row">
            <p class="h6 col-md-6 col-sm-12 col-lg-4 offset-lg-4 mx-auto mb-1 text-left  font-weight-bold">
                Fill this form to submit your request
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-sm-12 col-lg-6 mx-auto mt-2 mb-5">
            <form action="{% url 'contributors:create_contributor' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="id_name" class="col-sm-2 col-form-label text-right">Name</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" class="form-control" id="id_name" placeholder="Name" required>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="id_email" class="col-sm-2 col-form-label text-right">Email</label>
                    <div class="col-sm-10">
                        <input type="email" name="email" class="form-control" id="id_email" placeholder="Email"
                               required>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="id_contact" class="col-sm-2 col-form-label text-right">Contact</label>
                    <div class="col-sm-10">
                        <input type="tel" name="phone" maxlength="13" class="form-control" id="id_contact"
                               placeholder="Contact" required>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="id_about" class="col-sm-2 col-form-label text-right">About</label>
                    <div class="col-sm-10">
                        <textarea maxlength="200" class="form-control" rows="4" id="id_about" name="about"
                                  placeholder="short description about yourself" required></textarea>

                    </div>
                </div>

                <div class="form-group row">
                    <label for="{{ name }}" class="col-sm-2 col-form-label text-right">Role</label>
                    <div class="col-sm-10">

                        {% for value, name in form.fields.role.choices %}
                        <div class="custom-control custom-radio">
                            <input id="{{ name }}" name="role" value="{{ value }}" type="radio"
                                   class="form-control custom-control-input" required>
                            <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                        </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group row">
                    <label for="id_resume" class="col-sm-2 col-form-label text-right">Resume</label>
                    <div class="col-sm-10">
                        <input type="file" name="resume" id="id_resume" required>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10 offset-sm-2">
                        <input type="submit" class="btn btn-primary btn-sm ml-0 mt-0">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/contributors/home.html
{% extends "base.html" %}
{% block content %}
<div class="col-sm-12 col-md-8 col-lg-6 col-sm-12 mx-auto mb-5">
        <div class="card-body px-5 py-5 mt-5 text-center">
            <h5 class="font-weight-bold">Lets Build Together, Build Better</h5>
            <h5 class="my-4">open source projects are the driving force today for small startapp, enterprise to
                govt. organization.
                Lets work together and build better software.</h5>
            <a href="{% url 'contributors:contributor_list' %}" class="h5">Read the contributor list</a>
        </div>
</div>
{% endblock content %}

templates/contributors/thank_you.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-4 col-sm-12 col-lg-6 mx-auto  mb-5">
    <div class="card py-5 text-center">
        <div class="card-body">
            <h5 class="card-title">Thank you so much for submitting your request.
                we will get in touch with you shortly.</h5>
        </div>
    </div>
</div>
{% endblock content %}

templates/template_blocks/footers.html
<footer class="bg-light">
    <div class="container text-center">
        <p>Copyright &copy;
            <script>document.write(new Date().getFullYear());</script>
            , Nescode. All right reserved
        </p>
    </div>
</footer>

templates/template_blocks/head_css.html
{% load static %}
<title>{% block head_title %}Nescode Contributors{% endblock %}</title>
<link href="https://fonts.googleapis.com/css?family=EB+Garamond&display=swap" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
<link rel="icon" href="{% static 'images/nescode.jpg' %}">

templates/template_blocks/javascript.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

templates/template_blocks/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top mb-5 py-0">
    <a class="navbar-brand font-weight-bold" href="/">NESCODE</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link h5 text-primary" href="{% url 'contributors:create_contributor' %}">Join us to contribute
                </a>
            </li>
        </ul>
    </div>
</nav>